In [1]:
# 8 - 1
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
iris = load_iris()

In [4]:
# 8 - 2
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df = df.astype(float)
print(df)

df['label'] = iris.target
df['label'] = df.label.replace(dict(enumerate(iris.target_names)))
print(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

         label
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 5 columns]

In [5]:
# 8 - 3
label = pd.get_dummies(df['label'], prefix='label')
df = pd.concat([df, label], axis=1)
print(df)

df.drop(['label'], axis=1, inplace=True)
print(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

         label  label_setosa  label_versicolor  label_virginica
0       setosa             1                 0                0
1       setosa             1                 0                0
2       setosa             1                 0                0
3       setosa             1                 0                0
4       setosa             1                 0                0
..         ...           ...               ...              ...
145  virginica             0                 0                1
146  virginica             0                 0                1
147  virginica             0                 0                1
148  virginica             0                 0                1
149  virginica             0                 0                1

[150 rows x 8 columns]
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

     label_setosa  label_versicolor  label_virginica
0               1                 0                0
1               1                 0                0
2               1                 0                0
3               1                 0                0
4               1                 0                0
..            ...               ...              ...
145             0                 0                1
146             0                 0                1
147             0                 0                1
148             0                 0                1
149             0                 0                1

[150 rows x 7 columns]

In [8]:
# 8 - 4
X = df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]
X = np.asarray(X)
print(df)

y = df[['label_setosa', 'label_versicolor', 'label_virginica']]
y = np.asarray(y)
print(df)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

     label_setosa  label_versicolor  label_virginica
0               1                 0                0
1               1                 0                0
2               1                 0                0
3               1                 0                0
4               1                 0                0
..            ...               ...              ...
145             0                 0                1
146             0                 0                1
147             0                 0                1
148             0                 0                1
149             0                 0                1

[150 rows x 7 columns]
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

     label_setosa  label_versicolor  label_virginica
0               1                 0                0
1               1                 0                0
2               1                 0                0
3               1                 0                0
4               1                 0                0
..            ...               ...              ...
145             0                 0                1
146             0                 0                1
147             0                 0                1
148             0                 0                1
149             0                 0                1

[150 rows x 7 columns]

In [9]:
# 8 - 14
import tensorflow_datasets as tfds
import tensorflow as tf

In [37]:
# 8 - 15
(train_data, test_data), info = tfds.load(
    'imdb_reviews/subwords8k',
    split=(tfds.Split.TRAIN, tfds.Split.TEST),
    with_info=True,
    as_supervised=True
)

padded_shapes = ([None], ())
train_batches = train_data.shuffle(1000).padded_batch(10, padded_shapes=padded_shapes)
test_batches = test_data.shuffle(1000).padded_batch(10, padded_shapes=padded_shapes)

for _ in range(3):
  train_batch, train_labels = next(iter(train_batches))
  print(train_batch.numpy())
  print('\n')

WARNING:absl:TFDS datasets with text encoding are deprecated and will be removed in a future version. Instead, you should use the plain text version and tokenize the text using `tensorflow_text` (See: https://www.tensorflow.org/tutorials/tensorflow_text/intro#tfdata_example)

[[ 636    2   12 ...    0    0    0]
 [1179    6  208 ...    0    0    0]
 [ 387  381   57 ...    0    0    0]
 ...
 [7963 3923   34 ...    0    0    0]
 [4728 7974   14 ...    0    0    0]
 [ 133 2788    2 ...    0    0    0]]


[[2589 3171   36 ...    0    0    0]
 [  69    9  278 ... 7994 7972 7975]
 [  62    9    4 ...    0    0    0]
 ...
 [2988 1416   21 ...    0    0    0]
 [ 636    2   12 ...    0    0    0]
 [ 135 7968    8 ...    0    0    0]]


[[ 768  284 8002 ...    0    0    0]
 [  12  109 7968 ...    0    0    0]
 [  12  580   14 ...    0    0    0]
 ...
 [ 133  296   27 ...    0    0    0]
 [7924   14   32 ... 5695  136 7975]
 [  12  321    1 ...    0    0    0]]

In [46]:
dataset = tf.data.Dataset.range(11)
for window in dataset:
  print(window)
print('\n')

dataset = dataset.map(lambda x: tf.fill([tf.cast(x, tf.int32)], x))
for window in dataset:
  print(window)
print('\n')

dataset = dataset.padded_batch(2, padded_shapes=(None,))
for window in dataset:
  print(window)
print('\n')

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(10, shape=(), dtype=int64)


tf.Tensor([], shape=(0,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([2 2], shape=(2,), dtype=int64)
tf.Tensor([3 3 3], shape=(3,), dtype=int64)
tf.Tensor([4 4 4 4], shape=(4,), dtype=int64)
tf.Tensor([5 5 5 5 5], shape=(5,), dtype=int64)
tf.Tensor([6 6 6 6 6 6], shape=(6,), dtype=int64)
tf.Tensor([7 7 7 7 7 7 7], shape=(7,), dtype=int64)
tf.Tensor([8 8 8 8 8 8 8 8], shape=(8,), dtype=int64)
tf.Tensor([9 9 9 9 9 9 9 9 9], shape=(9,), dtype=int64)
tf.Tensor([10 10 10 10 10 10 10 10 10 10], shape=(10,), dtype=int64)


tf.Tensor(
[[0]
 [1]], shape=(2, 1), dtype=int64)
tf.Tensor(
[[2 2 0]
 [3 3 3]], shape=(2, 3), dtype=int64)
tf.Tensor(
[[4 4 4 4 0]
 [5 5 5 5 5]], shape=(2, 5), dtype=int64)
tf.Tensor(
[[6 6 6 6 6 6 0]
 [7 7 7 7 7 7 7]], shape=(2, 7), dtype=int64)
tf.Tensor(
[[8 8 8 8 8 8 8 8 0]
 [9 9 9 9 9 9 9 9 9]], shape=(2, 9), dtype=int64)
tf.Tensor([[10 10 10 10 10 10 10 10 10 10]], shape=(1, 10), dtype=int64)